@startuml
!include ./sprites.puml

package "Contract test" {
  rectangle "stub producer" <<$cog>> as tp
  queue ti <<$kafka >>
  [ServiceA1]
  rectangle verify <<$cog>>
}

note bottom of tp
  Using the stub producer
  provided by ServiceB1:
  The runtime producer
end note

database artifactory as ar {
 rectangle jars
}

ar -> tp: serviceB1-stub.jar
ar --> tp: kafka-schemas:7.3.0

tp -right-> ti: produces
ti -> [ServiceA1]: consumes
[ServiceA1] -> verify

@enduml