@startuml
!include ./sprites.puml
'!pragma layout smetana

package "Component test" {
  rectangle "mock producer" <<$cog>> as tp
  queue ti <<$kafka>>
  [ServiceA1]
  rectangle verify <<$cog>>
}

note bottom of tp
  Mocks ServiceA1 service:
  The runtime producer
end note

database artifactory as ar {
 rectangle jars
}

ar -> tp: kafka-schemas:7.3.0

tp -right-> ti: produces
ti -> [ServiceA1]: consumes
[ServiceA1] -> verify

@enduml