@startuml
!include ./sprites.puml

package "Contract test" as contractTest{
  rectangle "test code" <<$cog>> as tst
    database "H2 Database" as db {
     rectangle contracts {
        rectangle c1
     }
     rectangle outbox {
      rectangle o1
     }
     o1 -> c1
    }

  rectangle verify <<$cog>> as ver
  note bottom of db
   Contract service database
  end note
}

note bottom of ver
  Test code that verifies
  c1 and o1 exist in the DB
end note

database artifactory as ar {
 rectangle jars
}

note right of ar
contract-service-stub.jar is
produced by the producer contract
test of the Contract service
end note

tst --> db: creates schema and \n inserts c1 and o1
ar --> tst: contract-service-stub.jar
ver --> db: verifies c1 and o1

@enduml