@startuml
!include ./sprites.puml

package "ESP team" {
  [Kafka Schemas]
}

package "CRD team" {
  [RefData]
  [Contract]
  [RefData] --> [Contract]: queries
}

note top of [RefData]
A consumer of Contract and
a producer to Streams
end note

note left of [Contract]
A producer
to RefData
end note

package "MMC team" {
  [Streams]
}

note right of [Streams]
A consumer
of RefData
end note

database Artifactory {
 rectangle jars
}

queue ti <<$kafka>>

[RefData] --> ti: produces
ti --> [Streams]: consumes

Artifactory -up-> [RefData]: esp-kafka-schemas:7.4.0
Artifactory -up-> [Streams]: esp-kafka-schemas:7.3.0
[Kafka Schemas] --> Artifactory: publishes

@enduml