@startuml
!include ./sprites.puml

package "Contract test" {
  rectangle "trigger" <<$cog>> as tbl
  component RefData as refd {
    rectangle "contracts/ example \n messages" as con
  }
  queue ti <<$kafka >>
  rectangle verify <<$cog>> as ver
}

note left of tbl
  Tiggers business logic
end note

database artifactory as ar {
 rectangle jars
}

tbl -> refd
refd --> ti: produces
ver -> ar: intruments-stubs.jar
ti -> ver
ar --> refd: esp-kafka-schemas:7.4.0
con -> ver: "verifies \ncontracts"

@enduml