@startuml
!include ./sprites.puml

package "ESP team" {
  [Kafka Schemas]
}

package "CRD team" {
  [Instruments]
}

package "MMC team" {
  [Streams]
}

database Artifactory {
 rectangle jars
}

queue ti <<$kafka>>

[Instruments] --> ti: produces
ti --> [Streams]: consumes

Artifactory -up-> [Instruments]: esp-kafka-schemas:7.4.0
Artifactory -up-> [Streams]: esp-kafka-schemas:7.3.0
[Kafka Schemas] --> Artifactory: publishes

@enduml