@startuml
!include ./sprites.puml

package "Team C" {
  [Kafka Schemas]
}

package "Team B" {
  [ServiceB1]
  [ServiceB2]
  [ServiceB1] --> [ServiceB2]: queries
}

note top of [ServiceB1]
A consumer of ServiceB2 and
a producer to ServiceA1
end note

note left of [ServiceB2]
A producer
to ServiceB1
end note

package "Team A" {
  [ServiceA1]
}

note right of [ServiceA1]
A consumer
of ServiceB1
end note

database Artifactory {
 rectangle jars
}

queue ti <<$kafka>>

[ServiceB1] --> ti: produces
ti --> [ServiceA1]: consumes

Artifactory -up-> [ServiceB1]: kafka-schemas:7.4.0
Artifactory -up-> [ServiceA1]: kafka-schemas:7.3.0
[Kafka Schemas] --> Artifactory: publishes

@enduml