@startditaa
            +------------+ ------------------------------------------------------
            |  manual{tr}|  Exploratory, UX, complex business cases
            +------------+ ------------------------------------------------------
          +----------------+ ----------------------------------------------------
          |  end to end{tr}| API and UI level tests
          +----------------+ ----------------------------------------------------
        +--------------------+ --------------------------------------------------
        | cBLK contract{tr}  | Integration between services
        +--------------------+ --------------------------------------------------
      +------------------------+ ------------------------------------------------
      |        component{tr}   | Functionality of single component (microservice)
      +------------------------+ ------------------------------------------------
    +----------------------------+ ----------------------------------------------
    |            unit{tr}        | Scope of a single class
    +----------------------------+ ----------------------------------------------
@endditaa